### ISSUE TITLE
How can use this on Docker engine

### ISSUE THREAD

**Issue by DockerAsura** [CancerCollaboratory/billing#20]
Hi there,
Look's this project, am inserting the billing part.
after long search.., i found this project.

How can i use this on Docker engine level?

is there any user name password for this ? 

![754a5079121b4823](https://cloud.githubusercontent.com/assets/16235182/22877800/1adbf24e-f1fd-11e6-9af7-c7d51fa86386.jpg)

Reg
Asura

**Comment by andricDu** [comment]
Hi @DockerAsura , the project includes a Dockerfile that you can build a docker image with.

As for user accounts, it uses the same user accounts as whichever openstack you connect it to. The target openstack release is Mitaka.
