### ISSUE TITLE
Random discounts get applied to projects that have usage but user=null (deleted)

### ISSUE THREAD

**Issue by ra-ver** [CancerCollaboratory/billing#39]
4/2/2018  2:11:37 PM - info:  toDate=2018-04-01T00:00:00, imageCost=0.0418, image=624, fromDate=2018-03-01T00:00:00, user=null, projectId=af65ef84e8964123b0fe1190b530de6b

**Comment by b-f-chan** [comment]
This is a very rare case and has been difficult to reproduce.  We have monitored this for over a year and we have never observed or encountered it.  Let's close and re-open if it ever is reproduced concretely.  Closing ticket.
